# Generated by Django 4.1.13 on 2026-02-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_portfoliocategory_portfolioitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
    ]
