# Generated by Django 4.1.13 on 2026-02-26 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='master',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'master'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_as_master', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'master'}, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Мастера'),
        ),
    ]
