# Generated by Django 4.1.13 on 2026-02-26 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_booking_master_service_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, help_text='Сколько минут занимает услуга', verbose_name='Длительность (минут)'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('master', 'date', 'time')},
        ),
        migrations.CreateModel(
            name='MasterTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало перерыва')),
                ('end_time', models.TimeField(verbose_name='Конец перерыва')),
                ('reason', models.CharField(blank=True, help_text='Например: обед, личные дела', max_length=200, verbose_name='Причина')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='time_offs', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Перерыв мастера',
                'verbose_name_plural': 'Перерывы мастеров',
            },
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('slot_duration', models.IntegerField(default=60, help_text='Длительность слота в минутах', verbose_name='Длительность слота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Расписание мастера',
                'verbose_name_plural': 'Расписания мастеров',
                'unique_together': {('master', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='MasterException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_working', models.BooleanField(default=False, verbose_name='Работает?')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало работы')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец работы')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Причина')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Исключение в расписании',
                'verbose_name_plural': 'Исключения в расписании',
                'unique_together': {('master', 'date')},
            },
        ),
    ]
