# Generated by Django 4.1.13 on 2026-02-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_booking_status_service_duration_and_more'),
    ]

    operations = [
    ]
