# Generated by Django 4.1.13 on 2026-02-27 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0011_remove_mastertimeoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало перерыва')),
                ('end_time', models.TimeField(verbose_name='Конец перерыва')),
                ('reason', models.CharField(blank=True, default='Обед', max_length=200, verbose_name='Причина')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('master', models.ForeignKey(limit_choices_to={'role': 'master'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_time_offs', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Регулярный перерыв',
                'verbose_name_plural': 'Регулярные перерывы',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('master', 'day_of_week', 'start_time')},
            },
        ),
        migrations.DeleteModel(
            name='MasterTimeOff',
        ),
    ]
