# Generated by Django 4.1.13 on 2026-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_weeklytimeoff_delete_mastertimeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterexception',
            name='break_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва'),
        ),
        migrations.AddField(
            model_name='masterexception',
            name='break_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Причина перерыва'),
        ),
        migrations.AddField(
            model_name='masterexception',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало перерыва'),
        ),
        migrations.AlterField(
            model_name='masterexception',
            name='reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Причина исключения'),
        ),
    ]
