# Generated by Django 4.1.13 on 2026-04-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_masterexception_break_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
    ]
